platform:ios,'8.0'
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'TrySwift3.0' do
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'SnapKit', '~> 3.1.2'
pod 'HandyJSON', '~> 1.5.2'
pod 'Alamofire', '~> 4.3'
pod 'ReachabilitySwift'
end
